### PR TITLE
WIP: Support sentencepiece

### PR DESCRIPTION
**Pull request by Gastron**
This PR implements proper handling for sentencepiece-style gluing.

STATUS:
First implementation done, not tested atm.

### CODE REVIEW

**Comment by psmit** [comment]
Looks already pretty good. Would you have some toy example data for easy testing?

**Comment by Gastron** [comment]
I don't have toy data, but I think I can whip up a hand written lexicon_disambig example easily. I intend to create a very small FST at first, and create an image to see that it looks ok. Then I'll try some larger data and see that it compiles without problems.

**Comment by Gastron** [comment]
Ah, a slight annoyance. So with the other lfst scripts, you simply use the pronunciation from the lexiconp_disambig.txt. However, sentencepiece can place the space character anywhere (technically even inside subwords). The g2p mapper cannot handle the space character natively.

My current idea to solve this is to create a separate script that calls the g2p mapper for each subword part, stripped of the space characters, and then inserts special placeholder phones for the space character. A little ugly, but in practice I think that should work. I think I'll include that script here as it's pretty much necessary for using this script, if that's ok?

**Comment by psmit** [comment]
Sure, feel free to include it.

**Comment by Gastron** [comment]
Even with just one subword of all 4 possible "types", the resulting lexicon pic is quite large. Well, I'll try to decode this later:[
l_disambig
](url)

**Comment by Gastron** [comment]
This is ready to merge, though we should update the documentation. But I think the documentation needs a more general lookover (some legacy code in the examples), so maybe a separate PR.

**Comment by psmit** [comment]
Looks good indeed! One other gap in the documentation is that you should also fix "align_lexicon.xxx" in the phones directory, otherwise it is not possible to do phone alignment.

**Pull request merged**
